/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MAIN_MESSAGE_PB_H_INCLUDED
#define PB_MAIN_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ColorCommand {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
    uint32_t alpha;
} ColorCommand;

typedef struct _PressedCommand {
    bool pressed;
} PressedCommand;

typedef struct _ProtoMessage {
    uint32_t version;
    uint32_t sequence_number;
    pb_size_t which_payload;
    union {
        ColorCommand color;
        PressedCommand pressed;
    } payload;
} ProtoMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ColorCommand_init_default                {0, 0, 0, 0}
#define PressedCommand_init_default              {0}
#define ProtoMessage_init_default                {0, 0, 0, {ColorCommand_init_default}}
#define ColorCommand_init_zero                   {0, 0, 0, 0}
#define PressedCommand_init_zero                 {0}
#define ProtoMessage_init_zero                   {0, 0, 0, {ColorCommand_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ColorCommand_red_tag                     1
#define ColorCommand_green_tag                   2
#define ColorCommand_blue_tag                    3
#define ColorCommand_alpha_tag                   4
#define PressedCommand_pressed_tag               1
#define ProtoMessage_version_tag                 1
#define ProtoMessage_sequence_number_tag         2
#define ProtoMessage_color_tag                   3
#define ProtoMessage_pressed_tag                 4

/* Struct field encoding specification for nanopb */
#define ColorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3) \
X(a, STATIC,   SINGULAR, UINT32,   alpha,             4)
#define ColorCommand_CALLBACK NULL
#define ColorCommand_DEFAULT NULL

#define PressedCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     pressed,           1)
#define PressedCommand_CALLBACK NULL
#define PressedCommand_DEFAULT NULL

#define ProtoMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,color,payload.color),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pressed,payload.pressed),   4)
#define ProtoMessage_CALLBACK NULL
#define ProtoMessage_DEFAULT NULL
#define ProtoMessage_payload_color_MSGTYPE ColorCommand
#define ProtoMessage_payload_pressed_MSGTYPE PressedCommand

extern const pb_msgdesc_t ColorCommand_msg;
extern const pb_msgdesc_t PressedCommand_msg;
extern const pb_msgdesc_t ProtoMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ColorCommand_fields &ColorCommand_msg
#define PressedCommand_fields &PressedCommand_msg
#define ProtoMessage_fields &ProtoMessage_msg

/* Maximum encoded size of messages (where known) */
#define ColorCommand_size                        24
#define MAIN_MESSAGE_PB_H_MAX_SIZE               ProtoMessage_size
#define PressedCommand_size                      2
#define ProtoMessage_size                        38

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
